apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-crud-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jesuismarie/live-environments.git
    targetRevision: main
    path: aws/dev/user-crud-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: user-crud-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true