apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-crud-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/jesuismarie/user-crud-app.git
      targetRevision: main
      path: charts/user-crud-app
      helm:
        valueFiles:
          - $values/apps/user-crud-app/values-dev.yaml
    - repoURL: https://github.com/jesuismarie/live-environments.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: user-crud-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true